# Generated by Django 2.2 on 2019-04-03 04:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeruser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='registeruser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='registeruser',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='id',
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user',
            field=models.OneToOneField(max_length=40, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
