# Generated by Django 2.2 on 2019-04-08 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
