# Generated by Django 2.2 on 2019-04-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190403_0456'),
        ('property_operations', '0002_auto_20190408_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_description', models.TextField(max_length=200)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('enquiry_person_email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.RegisterUser')),
                ('enquiry_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_operations.Property')),
            ],
        ),
    ]
